### ISSUE TITLE
Integrate CodeQL to Jenkins pipeline and share result in Sonarqube

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#288]
start new Project in baloise-incubator

**Comment by arburk** [comment]
After further investigations and discussion with @Tiliavir I've decided to integrate the parser as Maven plugin instead of a Sonarqube plugin. Thus will also support Sonarcube cloud edition. Implementation has not yet finished, but drafted in incubator: See https://github.com/baloise-incubator/codeql2sonar-maven-plugin

**Comment by MarkusTiede** [comment]
Next steps
- pair-review
- add a bit of documentation
- open x day

**Comment by arburk** [comment]
created container to improve performance by factor 2 (tested internally in Jenkins for MFA)
-  https://hub.docker.com/r/arburk/codeql-analyzer-java
- https://github.com/baloise-incubator/codeql2sonar-maven-plugin/tree/main/docker
