### ISSUE TITLE
Used github action for releases in our java template was marked as unmaintained

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#302]
https://github.com/actions/create-release/issues/119

affected: https://github.com/baloise/repository-template-java/blob/master/.github/workflows/release.yml

**Comment by arburk** [comment]
As far as I've read by now, a separate action for releases might by obsolete since [GitHub cli](https://cli.github.com/manual/gh_release_create) is installed and available in actions. Thus the ```gh release create``` command can be used.

I've successfully tested this approach in private repo and adopted it here: https://github.com/baloise-incubator/codeql2sonar-maven-plugin/blob/main/.github/workflows/release.yml

- [ ] review 
- [ ] decide if approach should be adopted

**Comment by arburk** [comment]
As decided in todays bi-weekly, we will adopt suggested approach
